import type { Board, Member, TaskDetail, User } from './types';

const now = '2026-09-06T08:30:00.000Z';
export const demoUser: User = {
  id: 'u-ming',
  name: '三敏',
  email: 'ming@example.com',
  instanceAdmin: true,
};
const members: Member[] = [
  { ...demoUser, role: 'owner' },
  { id: 'u-lin', name: '林舟', email: 'lin@example.com', role: 'editor' },
  { id: 'u-sun', name: '孙悦', email: 'sun@example.com', role: 'viewer' },
];
const statuses = [
  {
    id: 's-todo',
    spaceId: 'space-work',
    name: '待办',
    semantic: 'todo' as const,
    position: 1,
    color: '#8b8b97',
    version: 1,
  },
  {
    id: 's-progress',
    spaceId: 'space-work',
    name: '进行中',
    semantic: 'in_progress' as const,
    position: 2,
    color: '#7c6df2',
    version: 1,
  },
  {
    id: 's-review',
    spaceId: 'space-work',
    name: '待验收',
    semantic: 'in_review' as const,
    position: 3,
    color: '#e89b3d',
    version: 1,
  },
  {
    id: 's-done',
    spaceId: 'space-work',
    name: '已完成',
    semantic: 'done' as const,
    position: 4,
    color: '#50ad80',
    version: 1,
  },
];
export const demoTasks = [
  {
    id: 't-27',
    spaceId: 'space-work',
    number: 27,
    title: '完成 Codex 桌面端看板入口',
    description: '在侧栏提供紧凑入口，保留原生项目导航。\n\n验收时确认窗口重载后入口仍可恢复。',
    statusId: 's-progress',
    priority: 1,
    assigneeId: 'u-ming',
    labels: ['桌面端', '首版'],
    checklist: [
      { id: 'c1', text: '入口注入', checked: true },
      { id: 'c2', text: '重载恢复', checked: false },
    ],
    repository: 'https://github.com/acme/codex-taskboard',
    blocked: false,
    blockedReason: '',
    position: 1000,
    version: 4,
    archived: false,
    updatedAt: now,
    createdAt: now,
  },
  {
    id: 't-26',
    spaceId: 'space-work',
    number: 26,
    title: '定义任务状态语义与验收流',
    description: '每个自定义列映射到固定状态语义，供 Agent 和成员统一理解。',
    statusId: 's-review',
    priority: 1,
    assigneeId: 'u-lin',
    labels: ['核心', 'API'],
    checklist: [
      { id: 'c3', text: '并发领取测试', checked: true },
      { id: 'c4', text: '验收接口', checked: true },
    ],
    repository: 'https://github.com/acme/codex-taskboard',
    blocked: false,
    blockedReason: '',
    position: 1000,
    version: 7,
    archived: false,
    updatedAt: now,
    createdAt: now,
  },
  {
    id: 't-25',
    spaceId: 'space-work',
    number: 25,
    title: '部署文档与首次管理员流程',
    description: '提供 Docker Compose、备份恢复及升级检查说明。',
    statusId: 's-todo',
    priority: 2,
    assigneeId: null,
    labels: ['文档'],
    checklist: [],
    repository: 'https://github.com/acme/codex-taskboard',
    blocked: false,
    blockedReason: '',
    position: 1000,
    version: 1,
    archived: false,
    updatedAt: now,
    createdAt: now,
  },
  {
    id: 't-24',
    spaceId: 'space-work',
    number: 24,
    title: '空间级实时同步',
    description: '使用 SSE 推送空间变更，撤销权限后立即断开。',
    statusId: 's-todo',
    priority: 0,
    assigneeId: 'u-sun',
    labels: ['同步', '安全'],
    checklist: [],
    repository: 'https://github.com/acme/codex-taskboard',
    blocked: true,
    blockedReason: '等待权限事件模型确认',
    position: 2000,
    version: 2,
    archived: false,
    updatedAt: now,
    createdAt: now,
  },
  {
    id: 't-23',
    spaceId: 'space-work',
    number: 23,
    title: '登录与邀请链接',
    description: '邀请链接一次性使用并支持过期。',
    statusId: 's-done',
    priority: 2,
    assigneeId: 'u-lin',
    labels: ['认证'],
    checklist: [],
    repository: null,
    blocked: false,
    blockedReason: '',
    position: 1000,
    version: 5,
    archived: false,
    updatedAt: now,
    createdAt: now,
  },
] as const;

export function makeDemoBoard(): Board {
  return {
    space: {
      id: 'space-work',
      name: '产品工作室',
      icon: '✦',
      color: '#7c6df2',
      description: 'Codex Taskboard 首版发布工作',
      version: 3,
      archived: false,
      role: 'owner',
    },
    statuses,
    tasks: demoTasks.map((t) => ({
      ...t,
      labels: [...t.labels],
      checklist: t.checklist.map((c) => ({ ...c })),
    })),
    members,
  };
}
export function makeDemoDetail(taskId: string): TaskDetail {
  const task = makeDemoBoard().tasks.find((t) => t.id === taskId) ?? makeDemoBoard().tasks[0];
  return {
    task,
    activities: [
      {
        id: 'a1',
        taskId: task.id,
        actorId: 'u-lin',
        actorName: '林舟',
        kind: 'comment',
        body: '接口契约已经整理好，前端可以直接对接。',
        createdAt: now,
      },
      {
        id: 'a2',
        taskId: task.id,
        actorId: 'u-ming',
        actorName: '三敏',
        kind: 'moved',
        body: '将任务移至进行中',
        createdAt: now,
      },
    ],
    executions:
      task.id === 't-27'
        ? [
            {
              id: 'e1',
              taskId: task.id,
              actorId: 'u-ming',
              deviceId: 'win-8c32',
              threadId: 'thread-demo',
              phase: 'running',
              summary: '正在实现桌面入口',
              verification: '',
              createdAt: now,
            },
          ]
        : [],
  };
}
