name: 功能建议
description: 提出使用场景和希望的行为
body:
  - type: textarea
    id: scenario
    attributes:
      label: 使用场景与问题
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: 希望的行为与可接受的取舍
